#!/usr/bin/env bash
# Slice S7 — Codex login (the primary brain).
#
# Codex is the primary model; it logs in via an INTERACTIVE OAuth device-code
# flow (you open a URL and enter a code, ~30 seconds). After login, the agent is
# reconfigured to Codex-primary with OpenRouter as the fallback.
#
# ⚠️ Codex refresh tokens are single-use — always log in FRESH per agent, never
# copy an auth.json between agents (it silently breaks both).
#
# Sourced after lib/config.sh (reuses config_home_channel). Entry: codex_install.
# Env: CODEX_MODEL (default gpt-5.5), CODEX_SKIP_LOGIN=1 to skip the interactive
# login (e.g. CI), APPLY_NETWORK gates the service restart.

# Interactive device-code login for Codex.
codex_login() {
  local user="$1" home="$2"
  local hermes="$home/.local/share/hermes-venv/bin/hermes"
  step "Codex login — interactive device-code flow (open the URL, enter the code)"
  if [ "${DRY_RUN:-0}" = "1" ]; then
    warn "would run (interactive): hermes auth add openai-codex --type oauth --no-browser"
    return 0
  fi
  if [ "${CODEX_SKIP_LOGIN:-0}" = "1" ]; then
    warn "CODEX_SKIP_LOGIN=1 — skipping the interactive Codex login"
    return 0
  fi
  # Runs interactively: prints a URL + code and polls until you authorize.
  run sudo -H -u "$user" env HERMES_HOME="$home/.hermes" "$hermes" auth add openai-codex --type oauth --no-browser
  # Confirm it took (don't silently continue on a half-finished login).
  if sudo -H -u "$user" env HERMES_HOME="$home/.hermes" "$hermes" auth status openai-codex 2>/dev/null | grep -qiE 'authenticated|logged in'; then
    log "Codex login confirmed"
  else
    warn "could not confirm Codex auth — the agent will fall back to OpenRouter until Codex is logged in"
  fi
}

# Rewrite config.yaml: Codex primary, OpenRouter fallback (keeps free-response + auto-approve).
codex_configure() {
  local user="$1" home="$2"
  local hc; hc="$(config_home_channel)"
  local out="$home/.hermes/config.yaml"
  step "Setting Codex as the primary brain (OpenRouter fallback) in ${out}"
  if [ "${DRY_RUN:-0}" = "1" ]; then
    warn "would set model.default=${CODEX_MODEL:-gpt-5.5} provider=openai-codex + openrouter fallback"
    return 0
  fi
  run install -d -o "$user" -g "$user" -m 0750 "$home/.hermes"
  ( umask 022
    cat > "$out" <<CFG
# Hermes config — generated by hermes-personal-agent-installer (Codex primary).
model:
  default: "${CODEX_MODEL:-gpt-5.5}"
  provider: "openai-codex"

# If Codex is unavailable, fall back to OpenRouter automatically.
fallback_providers:
  - provider: "openrouter"
    model: "${HERMES_MODEL:-openai/gpt-4o-mini}"

# Auto-approve tool use (only SLACK_ALLOWED_USERS can trigger the agent).
approvals:
  mode: "auto"

# Persistent memory: built-in MEMORY.md/USER.md + OpenViking as the external brain.
memory:
  memory_enabled: true
  user_profile_enabled: true
  provider: "openviking"

# The agent's home channel is its own space — replies to everything, no @mention.
slack:
  free_response_channels: "${hc}"
CFG
  )
  run chown "$user:$user" "$out"
  log "config.yaml set to Codex primary + OpenRouter fallback"
}

codex_install() {
  local user="${1:?codex_install: agent user required}"
  need_root
  local home; home="$(user_home "$user")"
  if [ -z "$home" ]; then
    [ "${DRY_RUN:-0}" = "1" ] || die "could not resolve home dir for '${user}'"
    home="/home/${user}"
  fi
  codex_login "$user" "$home"
  codex_configure "$user" "$home"
  # restart the gateway service so it picks up the new model + Codex auth
  if [ "${APPLY_NETWORK:-1}" = "1" ] && [ "${DRY_RUN:-0}" != "1" ] \
     && systemctl list-unit-files hermes-agent.service >/dev/null 2>&1; then
    run systemctl restart hermes-agent.service && log "gateway restarted on Codex"
  fi
  step "Codex configured as the primary brain."
}
