#!/usr/bin/env bash
# Slice S6 — agent config: the Hermes config.yaml, the SOUL ("who you are") and
# USER ("who I am") files, and the gateway as a persistent service.
#
# This codifies the manually-verified working setup: model via OpenRouter (Codex
# becomes primary once you log in — see the codex step), auto-approve, and
# free-response in the agent's own home channel (it replies to everything posted
# there, no @mention needed). Entry point: config_install.
#
# Env: HERMES_MODEL (default openai/gpt-4o-mini), APPLY_NETWORK (gate the actual
# service start, like harden).

# Resolve the agent's home Slack channel from the Agent 1P item (for free-response).
# Empty if it can't be resolved — then the agent just requires @mentions.
config_home_channel() {
  if [ -n "${SLACK_HOME_CHANNEL:-}" ] && ! printf '%s' "$SLACK_HOME_CHANNEL" | grep -q 'op://'; then
    printf '%s' "$SLACK_HOME_CHANNEL"; return 0
  fi
  if [ -n "${OP_SERVICE_ACCOUNT_TOKEN:-}" ] && have op; then
    op read "op://${OP_VAULT:-YOUR_VAULT}/Agent/home_channel" 2>/dev/null || true
  fi
}

config_render_config_yaml() {
  local user="$1" home="$2"
  local model="${HERMES_MODEL:-openai/gpt-4o-mini}"
  local hc; hc="$(config_home_channel)"
  local out="$home/.hermes/config.yaml"
  step "Writing ${out} (model=${model}, free-response home channel=${hc:-none})"
  if [ "${DRY_RUN:-0}" = "1" ]; then warn "would write ${out}"; return 0; fi
  run install -d -o "$user" -g "$user" -m 0750 "$home/.hermes"
  ( umask 022
    cat > "$out" <<CFG
# Hermes config — generated by hermes-personal-agent-installer.
# Model: runs on OpenRouter until you log in to Codex (then Codex is primary).
model:
  default: "${model}"

# Auto-approve tool use (only SLACK_ALLOWED_USERS can trigger the agent).
approvals:
  mode: "auto"

# Persistent memory: built-in MEMORY.md/USER.md + OpenViking as the external brain
# (the openviking step installs the server it points at).
memory:
  memory_enabled: true
  user_profile_enabled: true
  provider: "openviking"

# Slack: the agent's home channel is its own space — it replies to everything
# posted there, no @mention needed.
slack:
  free_response_channels: "${hc}"
CFG
  )
  run chown "$user:$user" "$out"
  log "config.yaml written"
}

# SOUL = "who you are" (the agent's persona). A starter the user edits.
config_render_soul() {
  local user="$1" home="$2"
  local out="$home/.hermes/SOUL.md"
  step "Writing starter SOUL (${out}) — 'who you are'"
  if [ "${DRY_RUN:-0}" = "1" ]; then warn "would write ${out}"; return 0; fi
  ( umask 022
    cat > "$out" <<'SOUL'
# SOUL — who you are
<!-- starter from hermes-personal-agent-installer; edit freely -->

You are a personal AI assistant. You live on your own server and run 24/7.

- Be direct and useful. Push back honestly when something is a bad idea —
  you are a thinking partner, not a yes-bot.
- Keep replies tight. No filler.
- You can run tools and code on this box; do so when it genuinely helps.

Edit this file to give yourself a name, a personality, and a role.
SOUL
  )
  run chown "$user:$user" "$out"
  log "SOUL.md written"
}

# USER = "who I am" (the agent learns about its owner). A template the user fills.
config_render_user() {
  local user="$1" home="$2"
  local out="$home/.hermes/USER.md"
  step "Writing starter USER file (${out}) — 'who I am'"
  if [ "${DRY_RUN:-0}" = "1" ]; then warn "would write ${out}"; return 0; fi
  ( umask 022
    cat > "$out" <<'USR'
# USER — who I am
<!-- starter from hermes-personal-agent-installer; fill this in -->

Tell your agent about you so it stops being generic and becomes *yours*:

- Who you are / what you do
- What you want help with day to day
- How you like to be helped (tone, detail level, what to never do)
- Useful context (time zone, tools you use, people/projects it should know)
USR
  )
  run chown "$user:$user" "$out"
  log "USER.md written"
}

# Install the gateway as a persistent systemd service (survives reboot).
# The service runs as the agent user, under `op run` so secrets resolve, reading
# the read-only SA token from a root-owned 0600 file.
config_install_service() {
  local user="$1" home="$2"
  local venv="$home/.local/share/hermes-venv"
  step "Installing the agent gateway as a service (hermes-agent.service)"
  if [ "${DRY_RUN:-0}" = "1" ]; then
    warn "would write /etc/hermes-agent/op.env + /etc/systemd/system/hermes-agent.service and start it"
    return 0
  fi
  # Persist the bootstrap SA token (the one secret that must live on disk) 0600 root.
  run install -d -m 0750 /etc/hermes-agent
  if [ -n "${OP_SERVICE_ACCOUNT_TOKEN:-}" ]; then
    ( umask 077; printf 'OP_SERVICE_ACCOUNT_TOKEN=%s\n' "$OP_SERVICE_ACCOUNT_TOKEN" > /etc/hermes-agent/op.env )
    run chmod 0600 /etc/hermes-agent/op.env
    log "wrote /etc/hermes-agent/op.env (0600, root)"
  else
    warn "OP_SERVICE_ACCOUNT_TOKEN not set — service will need it in /etc/hermes-agent/op.env to start"
  fi
  cat > /etc/systemd/system/hermes-agent.service <<UNIT
[Unit]
Description=Hermes Personal Agent gateway
After=network-online.target
Wants=network-online.target

[Service]
User=${user}
Environment=HERMES_HOME=${home}/.hermes
Environment=PYTHONUNBUFFERED=1
EnvironmentFile=/etc/hermes-agent/op.env
ExecStart=/usr/local/bin/op run --env-file ${home}/.hermes/op-secrets.env -- ${venv}/bin/hermes gateway run --replace
Restart=always
RestartSec=5
TimeoutStopSec=210

[Install]
WantedBy=multi-user.target
UNIT
  log "wrote /etc/systemd/system/hermes-agent.service"
  run systemctl daemon-reload
  if [ "${APPLY_NETWORK:-1}" = "1" ]; then
    run systemctl enable --now hermes-agent.service
    log "hermes-agent.service enabled + started"
  else
    warn "APPLY_NETWORK=0 — service installed but NOT started (start with: systemctl enable --now hermes-agent)"
  fi
}

config_install() {
  local user="${1:?config_install: agent user required}"
  need_root
  local home; home="$(user_home "$user")"
  if [ -z "$home" ]; then
    [ "${DRY_RUN:-0}" = "1" ] || die "could not resolve home dir for '${user}'"
    home="/home/${user}"
  fi
  config_render_config_yaml "$user" "$home"
  config_render_soul "$user" "$home"
  config_render_user "$user" "$home"
  config_install_service "$user" "$home"
  step "Config complete — agent configured + gateway service installed."
}
