#!/usr/bin/env bash
# Slice S4 — 1Password wiring (the one-item / two-SA secrets core).
#
# Model (see CONTEXT.md):
#   - ONE 1Password item holds every value (one place to fill, one to rotate).
#   - A READ-ONLY 1Password service account reads it. Its token is supplied via
#     the environment (OP_SERVICE_ACCOUNT_TOKEN) — never committed, never printed.
#   - The agent's runtime config is op:// REFERENCES ONLY; real secret values are
#     resolved at runtime with `op run --env-file ... -- ...`, never written to disk.
#
# Operator supplies (out of band — these are the keys TO 1Password, so they can't
# live in 1Password): OP_SERVICE_ACCOUNT_TOKEN, OP_VAULT, OP_ITEM.
#
# Sourced by install.sh after lib/common.sh. Entry point: secrets_install.

OP_CLI_VERSION_DEFAULT="2.31.1"

# Install the 1Password CLI (`op`) — direct signed-zip download, no apt repo.
secrets_install_op() {
  step "1Password CLI (op)"
  if have op; then
    log "op already installed ($(op --version 2>/dev/null))"
    return 0
  fi
  if [ "${DRY_RUN:-0}" = "1" ]; then
    warn "would install the 1Password CLI (op ${OP_CLI_VERSION:-$OP_CLI_VERSION_DEFAULT})"
    return 0
  fi
  local arch ver tmp
  case "$(uname -m)" in
    x86_64|amd64)  arch=amd64 ;;
    aarch64|arm64) arch=arm64 ;;
    *) die "unsupported architecture for the op CLI: $(uname -m)" ;;
  esac
  ver="${OP_CLI_VERSION:-$OP_CLI_VERSION_DEFAULT}"
  apt_install curl unzip ca-certificates
  tmp="$(mktemp -d)"
  run curl -sSfL "https://cache.agilebits.com/dist/1P/op2/pkg/v${ver}/op_linux_${arch}_v${ver}.zip" -o "${tmp}/op.zip"
  run unzip -o "${tmp}/op.zip" op -d "${tmp}"
  run install -m 0755 "${tmp}/op" /usr/local/bin/op
  run rm -rf "${tmp}"
  log "installed op $(op --version 2>/dev/null)"
}

# Render the agent's runtime env-file of op:// references. One Login item PER
# PLATFORM in the user's vault (OpenAI, OpenRouter, Agent, Slack, Tailscale,
# GitHub) — the item names are the STANDARD. No real values on disk; resolved at
# runtime by `op run`.
secrets_render_env() {
  local user="$1"
  local vault="${OP_VAULT:-YOUR_VAULT}"
  local home; home="$(user_home "$user")"
  if [ -z "$home" ]; then
    [ "${DRY_RUN:-0}" = "1" ] || die "could not resolve home dir for '${user}'"
    home="/home/${user}"
  fi
  local out="$home/.hermes/op-secrets.env"
  step "Rendering per-platform secret references -> ${out}  (vault=${vault})"
  if [ "${DRY_RUN:-0}" = "1" ]; then
    warn "would write ${out}: op:// references only (0600, owned by ${user})"
    return 0
  fi
  run install -d -o "$user" -g "$user" -m 0750 "$home/.hermes"
  ( umask 077
    cat > "$out" <<EOF
# Runtime secret REFERENCES for this agent — op:// only, no real secrets on disk.
# Resolved at runtime with:  op run --env-file "$out" -- <command>
# Generated by hermes-personal-agent-installer.  vault=${vault}
# One API Credential item PER PLATFORM (the STANDARD names; see examples/1password-item.example.md).
# Single-secret items use the native 'credential' field; multi-field items use named fields.
# --- brain (models); Codex is an interactive login, not a field ---
OPENROUTER_API_KEY="op://${vault}/OpenRouter/credential"
OPENAI_API_KEY="op://${vault}/OpenAI/credential"
# --- slack (Slack item = EVERYTHING Slack: tokens + who/where it talks) ---
SLACK_BOT_TOKEN="op://${vault}/Slack/bot_token"
SLACK_APP_TOKEN="op://${vault}/Slack/app_token"
SLACK_SIGNING_SECRET="op://${vault}/Slack/signing_secret"
SLACK_ALLOWED_USERS="op://${vault}/Slack/allowed_user"
SLACK_HOME_CHANNEL="op://${vault}/Slack/home_channel"
# --- backup ---
GITHUB_BACKUP_PAT="op://${vault}/GitHub/backup_pat"
GITHUB_BACKUP_REPO="op://${vault}/GitHub/backup_repo"
# --- networking ---
TAILSCALE_AUTHKEY="op://${vault}/Tailscale/credential"
EOF
  )
  run chown "$user:$user" "$out"
  run chmod 0600 "$out"
  log "wrote ${out} (0600, owned by ${user}) — references only"
}

# Verify the read-only service account can read EVERY required field — up front,
# so a wrong item/field name fails FAST here (with the exact ref) instead of
# halfway through the install at the gateway. Optional fields (GitHub/Tailscale)
# only warn. Needs OP_SERVICE_ACCOUNT_TOKEN; skipped (with guidance) if absent.
secrets_verify() {
  local user="$1"
  step "Verifying the 1Password service account can read every required field"
  if [ -z "${OP_SERVICE_ACCOUNT_TOKEN:-}" ]; then
    warn "OP_SERVICE_ACCOUNT_TOKEN not set — skipping verify. Set the read-only SA token to confirm access."
    return 0
  fi
  local home; home="$(user_home "$user")"; [ -n "$home" ] || home="/home/${user}"
  local envfile="$home/.hermes/op-secrets.env"
  if [ "${DRY_RUN:-0}" = "1" ]; then
    warn "would verify every op:// reference in ${envfile} resolves (fail-fast on a wrong field name)"
    return 0
  fi
  local missing=0 name val ref opt
  while IFS='=' read -r name val; do
    case "$name" in ''|\#*) continue ;; esac
    ref="$(printf '%s' "$val" | tr -d '"')"
    case "$ref" in op://*) ;; *) continue ;; esac
    case "$name" in GITHUB_BACKUP_*|TAILSCALE_AUTHKEY) opt=1 ;; *) opt=0 ;; esac
    if op read "$ref" >/dev/null 2>&1; then
      :
    elif [ "$opt" = 1 ]; then
      warn "optional field not found (fine to skip): ${name} -> ${ref}"
    else
      printf '  \342\234\227 MISSING/UNREADABLE: %s -> %s\n' "$name" "$ref" >&2
      missing=$((missing + 1))
    fi
  done < "$envfile"
  if [ "$missing" -gt 0 ]; then
    die "${missing} required 1Password field(s) above could not be read. The item + field names must match EXACTLY (this is the usual cause of a half-finished install). Fix them and re-run."
  fi
  log "all required 1Password references resolve ✓"
}

# Orchestrates the 1Password wiring slice.
secrets_install() {
  local user="${1:?secrets_install: agent user required}"
  need_root
  secrets_install_op
  secrets_render_env "$user"
  secrets_verify "$user"
  step "1Password wiring complete (op installed; per-platform references rendered + verified)."
}
